# Challenge 2 — Indexing & Slicing

Arrays aren’t useful until you can **select parts of them**.  
In this challenge you’ll learn how to read and write specific elements, rows, columns, ranges, boolean masks, and fancy picks — the stuff you use every day.


## ⏰ Quick preperation

**Run the following code block to install numpy and setup a visualization function.**

In [ ]:
import numpy as np

np.set_printoptions(
    linewidth=100,
    precision=3,
    suppress=True
)


def pretty(a, max_rows=6, max_cols=12, decimals=3):
    arr = np.array(a)
    with np.printoptions(precision=decimals, suppress=True):
        # use numpy’s built-in summarization (head/tail with …)
        txt = np.array2string(arr,
                              max_line_width=100,
                              threshold=max_rows*max_cols,
                              edgeitems=min(max_rows, max_cols))
    print(txt)
    return arr


def pretty_bool(a):
    chars = {True:"T", False:"F"}
    for row in a:
        print(" ".join(chars[v] for v in row))


## Section 1 — Basic Indexing

**Goal:** get comfortable with square brackets: single items, whole rows, whole columns, and small structural picks (like corners).  
**Rule:** no loops — use NumPy indexing.


### 🧩 Tasks
Write your functions below. Each one should return the described value(s).


In [ ]:
# Challenge 2 / Section 1 — Tasks

import numpy as np

def get_item_rc(a: np.ndarray, r: int, c: int):
    """
    Section 2.1 — Single item by row/col
    - Input: a 2D array 'a', zero-based row index 'r', col index 'c'.
    - Return: the single scalar at (r, c).
    - Notes: function should work for any numeric dtype/shape, as long as a.ndim==2.
    """
    raise NotImplementedError


def get_first_row_last_col(a: np.ndarray):
    """
    Section 2.1 — Whole row / whole column
    - Input: a 2D array 'a'.
    - Return: a tuple (row0, col_last)
        * row0 is the first row of 'a' (1D view, shape (a.shape[1],)).
        * col_last is the last column of 'a' (1D view, shape (a.shape[0],)).
    - Constraints: do not copy unnecessarily; rely on indexing.
    """
    raise NotImplementedError


def set_border_zeros(a: np.ndarray):
    """
    Section 2.1 — Write via indexing (border to zeros)
    - Input: a 2D array 'a' with shape (m, n) and m>=2, n>=2.
    - Task: set the entire border (top row, bottom row, left col, right col) to 0 **in-place**.
    - Return: the same array object 'a' after modification.
    - Notes: no loops; use indexing. Works with integer/float dtypes (0 must be valid).
    """
    raise NotImplementedError


def corners(a: np.ndarray):
    """
    Section 2.1 — Extract the four corners
    - Input: a 2D array 'a' with shape (m, n) and m>=2, n>=2.
    - Return: a 1D array of four elements in this order:
        [top-left, top-right, bottom-left, bottom-right]
    - No loops; use direct indexing with row/col positions.
    """
    raise NotImplementedError


### ✅ Tests
Run these after coding. If they pass, you’re solid on basic indexing.  
(We print outputs so students can see what’s expected *without* leaking exact targets in code.)


In [ ]:
# Section 2.1 tests — descriptive checks, no direct answers inside

# A reproducible base array to index from: 4x5 with distinct values
base = np.arange(20).reshape(4, 5)  # rows 0..3, cols 0..4

print("2.1 — Single item (r=2, c=3) — Output:")
val = get_item_rc(base, 2, 3)
# property checks: equals base[2,3], scalar-like, dtype preserved
assert np.isscalar(val) or (isinstance(val, np.ndarray) and val.shape == ()), "Must be a single scalar"
assert val == base[2, 3], "Value mismatch at (2,3)"
print(val)

print("\n2.1 — First row / Last col — Output:")
row0, col_last = get_first_row_last_col(base)
# shapes: row0 -> (5,), col_last -> (4,)
assert row0.ndim == 1 and row0.shape == (base.shape[1],), "row0 shape must match number of columns"
assert col_last.ndim == 1 and col_last.shape == (base.shape[0],), "col_last shape must match number of rows"
# values: row0 equals first row; col_last equals last column
assert np.array_equal(row0, base[0, :]), "row0 must equal the first row"
assert np.array_equal(col_last, base[:, -1]), "col_last must equal the last column"
print("row0:", row0)
print("col_last:", col_last)

print("\n2.1 — Set border to zeros (in-place) — Output:")
a = base.copy()
out = set_border_zeros(a)
# must be same object (in-place)
assert out is a, "Function must modify the input array in-place and return it"
# border should be 0; inner area unchanged
m, n = a.shape
# check top/bottom rows
assert np.all(a[0, :] == 0) and np.all(a[-1, :] == 0), "Top/bottom rows must be zeros"
# check left/right cols
assert np.all(a[:, 0] == 0) and np.all(a[:, -1] == 0), "Left/right columns must be zeros"
# inner should match original base
inner_ok = np.array_equal(a[1:-1, 1:-1], base[1:-1, 1:-1])
assert inner_ok, "Inner region must remain unchanged"
pretty(a)

print("\n2.1 — Corners [tl, tr, bl, br] — Output:")
cr = corners(base)
assert cr.ndim == 1 and cr.size == 4, "Return a 1D array of four elements"
expected = np.array([base[0, 0], base[0, -1], base[-1, 0], base[-1, -1]])
assert np.array_equal(cr, expected), "Order must be [tl, tr, bl, br]"
pretty(cr)

print("\nSection 2.1 passed! ✅")


Section 1 — Odds 11..29 — Output:
[11 13 15 17 19 21 23 25 27 29]

Section 1 — Linspace 0..1 (101 pts, float32) — Output:
[0.   0.01 0.02 0.03 0.04 0.05 ... 0.95 0.96 0.97 0.98 0.99 1.  ]

Section 1 — Logspace 10^0..10^3 (4 pts, float64) — Output:
[   1.   10.  100. 1000.]

Section 1 passed! ✅


### 🔎 Hints
*(peek only if you need a nudge)*  




- **Odds sequence:** you want numbers that increase by 2, starting at 11, and stopping just before 30.  
- **Even spacing (count-based):** think of dividing the interval [0, 1] into exactly 100 equal gaps, and include both ends.  
- **Log spacing:** you want 4 numbers that grow by powers of 10, starting at 1 and ending at 1000. Try the function that generates values evenly on a log scale.


### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*


In [ ]:
# Section 1 solutions

def make_odds_10_to_30():
    return np.arange(11, 30, 2)

def make_linspace_unit_interval_101():
    return np.linspace(0.0, 1.0, 101, dtype=np.float32)

def make_logspace_decades_0_to_3():
    return np.logspace(0, 3, 4, dtype=np.float64)


## Section 2 — DTypes & Initialization

Now that you can make simple arrays, the next step is to control **what type of data** goes inside them and how the array is **initialized**.  

In this section you’ll practice:  

- *creating arrays of zeros with a specific shape and dtype*
- *filling arrays with constants (like π) while keeping precision under control*
- *and generating integer ranges with small fixed-size dtypes*

The goal is to see that NumPy arrays aren’t just “numbers in boxes” — they carry **data type** information that changes how calculations behave.  

Don’t worry if you’ve never thought about dtypes before. The tasks will give you a **clear target output** and the tests will check if both the *values* and the *dtype* are correct.  

By the end of this section, you’ll be comfortable with **zeros, ones, full, and range arrays** — all with the exact dtype you choose.  


### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
# Section 2 tasks

def make_zeros_int16_3x2():
    """
    Section 2 — Zeros matrix
    - Return a 2D array with shape (3,2).
    - All values must be 0.
    - dtype must be int16.
    """
    raise NotImplementedError


def make_full_pi_float32_2x3():
    """
    Section 2 — Full of π
    - Return a 2D array with shape (2,3).
    - Every value equals π (within float32 precision).
    - dtype must be float32.
    """
    raise NotImplementedError


def make_int8_range_neg5_to_4():
    """
    Section 2 — Range -5..4
    - Return a 1D array of consecutive integers from -5 up to +4 (inclusive).
    - Step size = +1 (strictly increasing).
    - dtype must be int8.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [ ]:
# Section 2 tests

print("Section 2 — Zeros int16 (3x2) — Output:")
z = make_zeros_int16_3x2()
assert z.shape == (3,2), "Shape should be (3,2)"
assert z.dtype == np.int16, "dtype should be int16"
assert np.count_nonzero(z) == 0, "All values must be 0"
pretty(z)

print("\nSection 2 — Full of π (float32, 2x3) — Output:")
pi_mat = make_full_pi_float32_2x3()
assert pi_mat.shape == (2,3), "Shape should be (2,3)"
assert pi_mat.dtype == np.float32, "dtype should be float32"
assert np.allclose(pi_mat, np.float32(np.pi)), "All values should equal π (float32)"
pretty(pi_mat)

print("\nSection 2 — Int8 range -5..4 — Output:")
r = make_int8_range_neg5_to_4()
assert r.ndim == 1 and r.size == 10, "Should have 10 elements (-5..4)"
assert r.dtype == np.int8, "dtype should be int8"
assert r[0] == -5 and r[-1] == 4, "Endpoints should be -5 and 4"
assert np.all(r[1:] - r[:-1] == 1), "Must increase by +1"
pretty(r)

print("\nSection 2 passed! ✅")


Section 2 — Zeros int16 (3x2) — Output:
[[0 0]
 [0 0]
 [0 0]]

Section 2 — Full of π (float32, 2x3) — Output:
[[3.142 3.142 3.142]
 [3.142 3.142 3.142]]

Section 2 — Int8 range -5..4 — Output:
[-5 -4 -3 -2 -1  0  1  2  3  4]

Section 2 passed! ✅


### 🔎 Hints
*(peek only if you need a nudge)*  


- **Zeros with dtype:** there’s a constructor that creates an all-zeros array given a shape; you can set the dtype explicitly.
- **Fill with a constant:** prefer a constructor that fills an array with a single value in one shot; make sure the value and the array share the same precision.
- **Integer range:** think of creating a sequence from -5 up to (but not including) 5 and *fixing the dtype* to an 8-bit integer.

### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*

In [ ]:
# Section 2 solutions

def make_zeros_int16_3x2():
    return np.zeros((3, 2), dtype=np.int16)

def make_full_pi_float32_2x3():
    return np.full((2, 3), np.float32(np.pi), dtype=np.float32)

def make_int8_range_neg5_to_4():
    return np.arange(-5, 5, dtype=np.int8)


## Section 3 — Diagonals & Triangular Structure

Now that you can control dtypes and initialization, it’s time to play with **patterns inside arrays**.  

In this section you’ll practice:

- *building identity matrices with `eye`*  
- *adding custom values along diagonals*  
- *and making masks for lower/upper triangular shapes*  

These patterns are common in **linear algebra** and **matrix manipulations**.  
They’re also a great way to get used to NumPy’s indexing shortcuts.


### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
# Section 3 tasks

import numpy as np

def make_eye4():
    """
    Section 3 — Identity 4x4
    - Return a 2D array with shape (4,4).
    - Ones on the main diagonal.
    - Zeros everywhere else.
    - Any numeric dtype is fine.
    """
    raise NotImplementedError


def make_band_main_and_upper():
    """
    Section 3 — Banded (main=1, upper=3)
    - Return a 2D array with shape (4,4).
    - Main diagonal values == 1.
    - First upper diagonal (k=+1) values == 3.
    - All other positions == 0.
    - Any numeric dtype is fine.
    """
    raise NotImplementedError


def make_tril_mask5_exclusive():
    """
    Section 3 — Strict lower-triangular mask
    - Return a boolean 2D array with shape (5,5).
    - Below main diagonal (i > j) == True.
    - On/above main diagonal (i <= j) == False.
    - dtype must be bool.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [ ]:
# Section 3 tests

print("Section 3 — Identity 4x4 — Output:")
eye4 = make_eye4()
assert eye4.shape == (4,4), "Shape must be (4,4)"
assert np.all(eye4.diagonal() == 1), "Main diagonal must be ones"
assert np.count_nonzero(eye4) == 4, "Only 4 ones should exist"
pretty(eye4)

print("\nSection 3 — Banded (main=1, upper=3) — Output:")
band = make_band_main_and_upper()
assert band.shape == (4,4), "Shape must be (4,4)"
assert np.all(np.diag(band) == 1), "Main diagonal must be 1s"
assert np.all(np.diag(band, k=1) == 3), "First upper diagonal must be 3s"
mask_else = np.ones((4,4), dtype=bool)
np.fill_diagonal(mask_else, False)
mask_else[:-1,1:] = False  # exclude the upper diag from the 'else' region
assert np.all(band[mask_else] == 0), "Everything else must be 0"
pretty(band)

print("\nSection 3 — Strict lower-triangular mask (5x5) — Output:")
mask = make_tril_mask5_exclusive()
assert mask.shape == (5,5) and mask.dtype == bool, "Must be (5,5) bool mask"
i, j = np.indices(mask.shape)
assert np.all(mask[i <= j] == False), "Diagonal & above should be False"
assert np.all(mask[i > j] == True), "Below diagonal should be True"
pretty_bool(mask)

print("\nSection 3 passed! ✅")


Section 3 — Identity 4x4 — Output:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Section 3 — Banded (main=1, upper=3) — Output:
[[1. 3. 0. 0.]
 [0. 1. 3. 0.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]

Section 3 — Strict lower-triangular mask (5x5) — Output:
F F F F F
T F F F F
T T F F F
T T T F F
T T T T F

Section 3 passed! ✅


### 🔎 Hints
*(peek only if you need a nudge)*  

- **Identity matrix:** there’s a one-liner constructor for an “eye” with 1s on the main diagonal.  
- **Banded matrix:** try adding two arrays together — one for the main diagonal, one shifted up by 1.  
- **Lower-triangular mask:** there’s a helper that fills below the diagonal with ones; give it `k=-1` to exclude the diagonal and set `dtype=bool`.


### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*

In [ ]:
# Section 3 solutions

def make_eye4():
    return np.eye(4)

def make_band_main_and_upper():
    return np.eye(4) + np.diag(np.full(3, 3), k=1)

def make_tril_mask5_exclusive():
    return np.tril(np.ones((5,5), dtype=bool), k=-1)


## Section 4 — Reshape & Memory Order

You’ve made arrays and built patterns; now let’s shape them **in memory**.  
In this section you’ll practice:

- *reshaping in C-order (row-major)*  
- *reshaping in Fortran-order (column-major)*  
- *and building an array from raw bytes (no loops)*  

Understanding layout matters for performance, interop, and how values land when you reshape.

### 💡 Info — C-contiguous vs F-contiguous

When reshaping, NumPy needs to decide how values are laid out in memory:

- **C-contiguous (row-major)** → default in NumPy. Values are stored row by row.  
  Example 2×3: stored as `[1, 2, 3, 4, 5, 6]`.  
- **F-contiguous (column-major)** → Values are stored column by column.  
  Same 2×3: stored as `[1, 4, 2, 5, 3, 6]`.

Why it matters: performance (cache-friendly iteration), interop with other languages, and reshaping results.  
👉 In practice, it affects **speed of operations** and **compatibility with external libraries**.


### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
# Section 4 tasks

import numpy as np

def make_reshape_c_order():
    """
    Section 4 — C-order reshape
    - Start from the sequence [0, 1, 2, 3, 4, 5].
    - Reshape into a 2D array with shape (2, 3) using default (row-major / C-order).
    - Expected row layout (conceptually): first row has the first three values, second row the next three.
    - The result should be C-contiguous in memory.
    """
    arr = np.arange(6)
    arr = arr.reshape((2, 3), order='C')
    return arr


def make_reshape_f_order():
    """
    Section 4 — Fortran-order reshape
    - Start from the sequence [1, 2, 3, 4, 5, 6].
    - Reshape into a 2D array with shape (2, 3) using column-major (Fortran) order.
    - Expected column layout (conceptually): first column is [1, 2], second [3, 4], third [5, 6].
    - The result should be Fortran-contiguous in memory.
    """
    arr = np.arange(1, 7)
    arr = arr.reshape((2, 3), order='F')
    return arr


def make_frombuffer_uint8():
    """
    Section 4 — From raw bytes
    - Construct an array of dtype uint8 from the bytes b"\x01\x02\x03\x04".
    - The result should be a 1D array with those four values, in order.
    - No Python loops.
    """
    data = b"\x01\x02\x03\x04"
    return np.frombuffer(data, dtype=np.uint8)


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [ ]:
# Section 4 tests

print("Section 4 — C-order reshape (2x3) — Output:")
c = make_reshape_c_order()
assert c.shape == (2, 3), "Shape must be (2,3)"
# C-order property: raveling in C order should give 0..5
c_flat = c.ravel(order="C")
assert c_flat.size == 6 and c_flat[0] == 0 and c_flat[-1] == 5, "Values should start at 0 and end at 5"
# Row-major layout: first row < second row in value sequence
assert np.all(c[0] < c[1]), "First row should contain smaller sequential values than second row"
assert c.flags["C_CONTIGUOUS"], "Array should be C-contiguous"
pretty(c)

print("\nSection 4 — Fortran-order reshape (2x3) — Output:")
f = make_reshape_f_order()
assert f.shape == (2, 3), "Shape must be (2,3)"
# Fortran-order property: raveling in F order should give 1..6
f_flat = f.ravel(order="F")
assert f_flat.size == 6 and f_flat[0] == 1 and f_flat[-1] == 6, "Values should start at 1 and end at 6"
# Column-major layout: each column increases top→bottom
for col in range(f.shape[1]):
    assert f[0, col] < f[1, col], "Column values should increase down each column"
assert np.isfortran(f), "Array should be Fortran-contiguous"
pretty(f)

print("\nSection 4 — From raw bytes (uint8) — Output:")
buf = make_frombuffer_uint8()
assert buf.ndim == 1 and buf.size == 4, "Should be 1D length-4"
assert buf.dtype == np.uint8, "dtype should be uint8"
assert buf[0] == 1 and buf[-1] == 4, "Should contain 1..4"
assert np.all(buf[1:] - buf[:-1] == 1), "Should increase by +1 across elements"
pretty(buf)

print("\nSection 4 passed! ✅")


Section 4 — C-order reshape (2x3) — Output:
[[0 1 2]
 [3 4 5]]

Section 4 — Fortran-order reshape (2x3) — Output:
[[1 3 5]
 [2 4 6]]

Section 4 — From raw bytes (uint8) — Output:
[1 2 3 4]

Section 4 passed! ✅


### 🔎 Hints
*(peek only if you need a nudge)*

- **C-order reshape:** default reshape is row-major — think “fill rows left→right.”  
- **Fortran-order reshape:** specify the memory order flag to fill columns top→bottom.  
- **From raw bytes:** there’s a constructor that views a `bytes` object as an array without copying; make sure to set the dtype to 8-bit unsigned.

### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*

In [ ]:
# Section 4 solutions

def make_reshape_c_order():
    a = np.arange(6)               # [0,1,2,3,4,5]
    return a.reshape(2, 3)         # C-order by default

def make_reshape_f_order():
    a = np.arange(1, 7)            # [1,2,3,4,5,6]
    return a.reshape(2, 3, order="F")

def make_frombuffer_uint8():
    return np.frombuffer(b"\x01\x02\x03\x04", dtype=np.uint8)


## Section 5 — Stacking & Splitting

You can make arrays — now let’s **compose** them.  
In this section you’ll practice:

- *stacking rows and columns*  
- *stacking along a new depth axis*  
- *and splitting arrays back into equal parts*

This is the glue you’ll use to assemble mini-datasets and to break them down again.


### 🧩 Tasks
Write your functions below. Each one should return the described object.


In [ ]:
# Section 5 tasks

import numpy as np

def make_vstack_rows_2x3():
    """
    Section 5 — Vertical stack (rows)
    - Create two 1D arrays: [1, 2, 3] and [4, 5, 6].
    - Stack them as rows to form a 2D array with shape (2, 3).
    - Row 0 should contain the first three numbers; row 1 the next three.
    """
    raise NotImplementedError


def make_hstack_cols_3x2():
    """
    Section 5 — Horizontal stack (columns)
    - Create two column vectors of shape (3, 1):
        col1 = [1, 2, 3]^T
        col2 = [10, 20, 30]^T
    - Stack them side-by-side to form shape (3, 2), with col1 then col2.
    """
    raise NotImplementedError


def make_stack_depth_2x2x2():
    """
    Section 5 — Stack along depth
    - Create two 2x2 arrays:
        A = [[1, 0],
             [0, 1]]      (identity pattern)
        B = [[2, 2],
             [2, 2]]      (all twos)
    - Stack them along a NEW last axis to get shape (2, 2, 2)
      so that out[:, :, 0] == A and out[:, :, 1] == B.
    """
    raise NotImplementedError


def make_split_1d_5_equal():
    """
    Section 5 — Split into equal chunks
    - Create a 1D array with integers 0..19 (inclusive).
    - Split it into 5 equal consecutive chunks (each length 4).
    - Return a tuple (chunk0, chunk1, chunk2, chunk3, chunk4).
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.


In [ ]:
# Section 5 tests

print("Section 5 — vstack rows (2x3) — Output:")
vs = make_vstack_rows_2x3()
assert vs.shape == (2, 3), "Shape must be (2,3)"
# Row-wise properties
assert np.all(vs[0, 1:] - vs[0, :-1] == 1), "Row 0 must increase by +1"
assert np.all(vs[1, 1:] - vs[1, :-1] == 1), "Row 1 must increase by +1"
assert vs[0, 0] == 1 and vs[1, -1] == 6, "Row starts/ends should be 1 and 6"
pretty(vs)

print("\nSection 5 — hstack cols (3x2) — Output:")
hs = make_hstack_cols_3x2()
assert hs.shape == (3, 2), "Shape must be (3,2)"
# Column-wise properties
assert np.all(hs[1:, 0] - hs[:-1, 0] == 1), "First column must increase by +1 downwards"
assert np.all(hs[1:, 1] - hs[:-1, 1] == 10), "Second column must increase by +10 downwards"
assert hs[0, 0] == 1 and hs[-1, 1] == 30, "Column endpoints should be 1 and 30"
pretty(hs)

print("\nSection 5 — stack depth (2x2x2) — Output:")
depth = make_stack_depth_2x2x2()
assert depth.shape == (2, 2, 2), "Shape must be (2,2,2)"
# Depth properties: first slice looks like identity, second all twos
d0, d1 = depth[:, :, 0], depth[:, :, 1]
assert np.all(d0.diagonal() == 1) and np.count_nonzero(d0) == 2, "First depth slice should be identity-like"
assert np.all(d1 == 2), "Second depth slice should be all twos"
pretty(depth)

print("\nSection 5 — split 1D into 5 equal chunks — Output:")
chunks = make_split_1d_5_equal()
assert isinstance(chunks, (list, tuple)) and len(chunks) == 5, "Should return 5 chunks"
lengths = [c.size for c in chunks]
assert all(L == 4 for L in lengths), "Each chunk must have length 4"
# Continuity across chunks
first_vals = [c[0] for c in chunks]
last_vals  = [c[-1] for c in chunks]
assert first_vals[0] == 0 and last_vals[-1] == 19, "Overall range must be 0..19"
for i in range(4):
    assert first_vals[i+1] == last_vals[i] + 1, "Chunks must be consecutive"
# Show outputs
for idx, c in enumerate(chunks):
    print(f"chunk {idx}:")
    pretty(c)

print("\nSection 5 passed! ✅")


Section 5 — vstack rows (2x3) — Output:
[[1 2 3]
 [4 5 6]]

Section 5 — hstack cols (3x2) — Output:
[[ 1 10]
 [ 2 20]
 [ 3 30]]

Section 5 — stack depth (2x2x2) — Output:
[[[1 2]
  [0 2]]

 [[0 2]
  [1 2]]]

Section 5 — split 1D into 5 equal chunks — Output:
chunk 0:
[0 1 2 3]
chunk 1:
[4 5 6 7]
chunk 2:
[ 8  9 10 11]
chunk 3:
[12 13 14 15]
chunk 4:
[16 17 18 19]

Section 5 passed! ✅


### 🔎 Hints
*(peek only if you need a nudge)*


- **Stacking rows vs columns:** think `vstack` (one row on top of another) and `hstack` (columns side-by-side).  
- **Column vectors:** give them shape `(n, 1)` — reshaping or `np.newaxis` can help.  
- **Depth stacking:** adding a new axis means “wrap both arrays together” — look for a function that stacks along an axis you choose.  
- **Equal splits:** when the total length divides evenly by the number of parts, use the strict split (not the version that tolerates uneven sizes).


### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*


In [ ]:
# Section 5 solutions

def make_vstack_rows_2x3():
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    return np.vstack([a, b])

def make_hstack_cols_3x2():
    col1 = np.array([1, 2, 3]).reshape(-1, 1)
    col2 = np.array([10, 20, 30]).reshape(-1, 1)
    return np.hstack([col1, col2])

def make_stack_depth_2x2x2():
    A = np.array([[1, 0],
                  [0, 1]])
    B = np.full((2, 2), 2)
    return np.stack([A, B], axis=-1)

def make_split_1d_5_equal():
    arr = np.arange(20)  # 0..19
    parts = np.split(arr, 5)  # equal chunks only
    return tuple(parts)
