# Challenge 1 — Creating Your First Arrays

Welcome to the very first challenge!  
Before we can do anything interesting with NumPy, we need to know how to **make arrays**.  

In this challenge you’ll practice building arrays in different ways:  

- turning a Python list into a NumPy array
- generating sequences of numbers
- filling shapes with zeros, ones, or constants
- and trying a few tricks with diagonals and reshaping

Don’t worry if this feels new — every task will give you a **clear goal** and **instant feedback**.  
Your job is just to try writing the array, run the tests, and adjust until it works.

Think of this as your **“Hello World” moment with NumPy** — by the end you’ll be comfortable making the **building blocks** we’ll use in every other challenge.  


## 👀 Worked Example — Arrays from a Python List

Let’s warm up with the simplest possible task:
Take a regular Python list and turn it into a NumPy array.

This shows you the basic pattern we’ll repeat throughout the drills:

1. Write your function.
2. Run the tests.
3. Adjust until everything passes.

In [5]:
import numpy as np

def example_make_array_from_list():
    """Return a NumPy array created from [1, 2, 3, 4, 5]."""
    return np.array([1, 2, 3, 4, 5])


### ✅ Test it

In [6]:
assert np.array_equal(example_make_array_from_list(), np.array([1,2,3,4,5]))
print("It works! ✅")

It works! ✅


## Section 1 — Sequences & Spacing

**What you’ll do:** generate number sequences three different ways.  
- *`np.arange` → step-based*
- *`np.linspace` → count-based*
- *`np.logspace` → log-scaled*

These three patterns are the backbone of synthetic data, grid search, and plotting.

### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [72]:
# Section 1 tasks

import numpy as np

def make_odds_10_to_30():
    """
    Section 1 — Odds 11..29
    - Return a 1D array of odd integers strictly between 10 and 30.
    - Starts at 11 and ends at 29.
    - Step size = +2 (strictly increasing).
    """
    raise NotImplementedError


def make_linspace_unit_interval_101():
    """
    Section 1 — Linspace 0..1
    - Return a 1D array of length 101.
    - First value = 0.0, last value = 1.0.
    - Even spacing throughout (constant difference).
    - dtype must be float32.
    """
    raise NotImplementedError


def make_logspace_decades_0_to_3():
    """
    Section 1 — Logspace 10^0..10^3
    - Return a 1D array of length 4.
    - First value = 1 (10^0), last value = 1000 (10^3).
    - Constant ratio between consecutive values (×10).
    - dtype must be float64.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.


In [3]:
from tests.challenge_01 import section_01 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 1 failed")


Section 1 tests:

--- Odds 11..29 ---
✅ odds: 1D array
✅ odds: size 10
✅ odds: first=11, last=29
✅ odds: all odd
Output:
[11 13 15 17 19 21 23 25 27 29]

--- Linspace 0..1 (101 pts) ---
✅ linspace: length 101
✅ linspace: dtype float32
✅ linspace: endpoints 0 and 1
Output:
[0.   0.01 0.02 0.03 0.04 0.05 ... 0.95 0.96 0.97 0.98 0.99 1.  ]

--- Logspace 10^0..10^3 ---
✅ logspace: length 4
✅ logspace: dtype float64
✅ logspace: endpoints 1 and 1000
Output:
[   1.   10.  100. 1000.]


### 🔎 Hints
*(peek only if you need a nudge)*  




- **Odds sequence:** you want numbers that increase by 2, starting at 11, and stopping just before 30.  
- **Even spacing (count-based):** think of dividing the interval [0, 1] into exactly 100 equal gaps, and include both ends.  
- **Log spacing:** you want 4 numbers that grow by powers of 10, starting at 1 and ending at 1000. Try the function that generates values evenly on a log scale.


### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*


In [ ]:
# Section 1 solutions

def make_odds_10_to_30():
    return np.arange(11, 30, 2)

def make_linspace_unit_interval_101():
    return np.linspace(0.0, 1.0, 101, dtype=np.float32)

def make_logspace_decades_0_to_3():
    return np.logspace(0, 3, 4, dtype=np.float64)


## Section 2 — DTypes & Initialization

Now that you can make simple arrays, the next step is to control **what type of data** goes inside them and how the array is **initialized**.  

In this section you’ll practice:  

- *creating arrays of zeros with a specific shape and dtype*
- *filling arrays with constants (like π) while keeping precision under control*
- *and generating integer ranges with small fixed-size dtypes*

The goal is to see that NumPy arrays aren’t just “numbers in boxes” — they carry **data type** information that changes how calculations behave.  

Don’t worry if you’ve never thought about dtypes before. The tasks will give you a **clear target output** and the tests will check if both the *values* and the *dtype* are correct.  

By the end of this section, you’ll be comfortable with **zeros, ones, full, and range arrays** — all with the exact dtype you choose.  


### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
# Section 2 tasks

import numpy as np

def make_zeros_int16_3x2():
    """
    Section 2 — Zeros matrix
    - Return a 2D array with shape (3,2).
    - All values must be 0.
    - dtype must be int16.
    """
    raise NotImplementedError


def make_full_pi_float32_2x3():
    """
    Section 2 — Full of π
    - Return a 2D array with shape (2,3).
    - Every value equals π (within float32 precision).
    - dtype must be float32.
    """
    raise NotImplementedError


def make_int8_range_neg5_to_4():
    """
    Section 2 — Range -5..4
    - Return a 1D array of consecutive integers from -5 up to +4 (inclusive).
    - Step size = +1 (strictly increasing).
    - dtype must be int8.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [3]:
from tests.challenge_01 import section_02 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 1 failed")


Section 2 tests:

--- Zeros int16 (3x2) ---
✅ zeros: shape (3,2)
✅ zeros: dtype int16
✅ zeros: all 0
Output:
[[0 0]
 [0 0]
 [0 0]]

--- Full of π float32 (2x3) ---
✅ pi: shape (2,3)
✅ pi: dtype float32
✅ pi: values equal π
Output:
[[3.142 3.142 3.142]
 [3.142 3.142 3.142]]

--- Range -5..4 int8 ---
✅ range: length 10
✅ range: dtype int8
✅ range: endpoints -5 and 4
✅ range: consecutive +1
Output:
[-5 -4 -3 -2 -1  0  1  2  3  4]


### 🔎 Hints
*(peek only if you need a nudge)*  


- **Zeros with dtype:** there’s a constructor that creates an all-zeros array given a shape; you can set the dtype explicitly.
- **Fill with a constant:** prefer a constructor that fills an array with a single value in one shot; make sure the value and the array share the same precision.
- **Integer range:** think of creating a sequence from -5 up to (but not including) 5 and *fixing the dtype* to an 8-bit integer.

### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*

In [2]:
# Section 2 solutions

def make_zeros_int16_3x2():
    return np.zeros((3, 2), dtype=np.int16)

def make_full_pi_float32_2x3():
    return np.full((2, 3), np.float32(np.pi), dtype=np.float32)

def make_int8_range_neg5_to_4():
    return np.arange(-5, 5, dtype=np.int8)


## Section 3 — Diagonals & Triangular Structure

Now that you can control dtypes and initialization, it’s time to play with **patterns inside arrays**.  

In this section you’ll practice:

- *building identity matrices with `eye`*  
- *adding custom values along diagonals*  
- *and making masks for lower/upper triangular shapes*  

These patterns are common in **linear algebra** and **matrix manipulations**.  
They’re also a great way to get used to NumPy’s indexing shortcuts.


### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
# Section 3 tasks

import numpy as np

def make_eye4():
    """
    Section 3 — Identity 4x4
    - Return a 2D array with shape (4,4).
    - Ones on the main diagonal.
    - Zeros everywhere else.
    - Any numeric dtype is fine.
    """
    raise NotImplementedError


def make_band_main_and_upper():
    """
    Section 3 — Banded (main=1, upper=3)
    - Return a 2D array with shape (4,4).
    - Main diagonal values == 1.
    - First upper diagonal (k=+1) values == 3.
    - All other positions == 0.
    - Any numeric dtype is fine.
    """
    raise NotImplementedError


def make_tril_mask5_exclusive():
    """
    Section 3 — Strict lower-triangular mask
    - Return a boolean 2D array with shape (5,5).
    - Below main diagonal (i > j) == True.
    - On/above main diagonal (i <= j) == False.
    - dtype must be bool.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [11]:
from tests.challenge_01 import section_03 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 1 failed")


Section 3 tests:

--- Identity matrix (4x4) ---
✅ eye4: shape (4,4)
✅ eye4: diagonal ones
✅ eye4: only 4 ones
Output:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

--- Banded matrix (diag=1, upper=3) ---
✅ band: shape (4,4)
✅ band: main diag=1
✅ band: upper diag=3
✅ band: elsewhere 0
Output:
[[1. 3. 0. 0.]
 [0. 1. 3. 0.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]

--- Strict lower-triangular mask (5x5) ---
✅ mask: shape (5,5), dtype=bool
✅ mask: diag+above False
❌ mask: below True
Output:
F F F F F
F F F F F
F F F F F
F F F F F
F F F F F


AssertionError: Section 1 failed

### 🔎 Hints
*(peek only if you need a nudge)*  

- **Identity matrix:** there’s a one-liner constructor for an “eye” with 1s on the main diagonal.  
- **Banded matrix:** try adding two arrays together — one for the main diagonal, one shifted up by 1.  
- **Lower-triangular mask:** there’s a helper that fills below the diagonal with ones; give it `k=-1` to exclude the diagonal and set `dtype=bool`.


### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*

In [4]:
# Section 3 solutions

def make_eye4():
    return np.eye(4)

def make_band_main_and_upper():
    return np.eye(4) + np.diag(np.full(3, 3), k=1)

def make_tril_mask5_exclusive():
    return np.tril(np.ones((5,5), dtype=bool), k=-1)


## Section 4 — Reshape & Memory Order

You’ve made arrays and built patterns; now let’s shape them **in memory**.  
In this section you’ll practice:

- *reshaping in C-order (row-major)*  
- *reshaping in Fortran-order (column-major)*  
- *and building an array from raw bytes (no loops)*  

Understanding layout matters for performance, interop, and how values land when you reshape.

### 💡 Info — C-contiguous vs F-contiguous

When reshaping, NumPy needs to decide how values are laid out in memory:

- **C-contiguous (row-major)** → default in NumPy. Values are stored row by row.  
  Example 2×3: stored as `[1, 2, 3, 4, 5, 6]`.  
- **F-contiguous (column-major)** → Values are stored column by column.  
  Same 2×3: stored as `[1, 4, 2, 5, 3, 6]`.

Why it matters: performance (cache-friendly iteration), interop with other languages, and reshaping results.  
👉 In practice, it affects **speed of operations** and **compatibility with external libraries**.


### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [1]:
# Section 4 tasks

import numpy as np

def make_reshape_c_order():
    """
    Section 4 — C-order reshape
    - Start from the sequence [0, 1, 2, 3, 4, 5].
    - Reshape into a 2D array with shape (2, 3) using default (row-major / C-order).
    - Expected row layout (conceptually): first row has the first three values, second row the next three.
    - The result should be C-contiguous in memory.
    """
    raise NotImplementedError


def make_reshape_f_order():
    """
    Section 4 — Fortran-order reshape
    - Start from the sequence [1, 2, 3, 4, 5, 6].
    - Reshape into a 2D array with shape (2, 3) using column-major (Fortran) order.
    - Expected column layout (conceptually): first column is [1, 2], second [3, 4], third [5, 6].
    - The result should be Fortran-contiguous in memory.
    """
    raise NotImplementedError


def make_frombuffer_uint8():
    """
    Section 4 — From raw bytes
    - Construct an array of dtype uint8 from the bytes b"\x01\x02\x03\x04".
    - The result should be a 1D array with those four values, in order.
    - No Python loops.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [3]:
from tests.challenge_01 import section_04 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 1 failed")


Section 4 tests:

--- C-order reshape (0..5 → 2x3) ---
✅ C-order: shape (2,3)
✅ C-order: C-contiguous
✅ C-order: row layout matches
Output:
[[0 1 2]
 [3 4 5]]

--- Fortran-order reshape (1..6 → 2x3) ---
✅ F-order: shape (2,3)
✅ F-order: Fortran-contiguous
✅ F-order: column layout matches
Output:
[[1 3 5]
 [2 4 6]]

--- From raw bytes (uint8) ---
✅ frombuffer: length 4
✅ frombuffer: dtype uint8
✅ frombuffer: values [1,2,3,4]
Output:
[1 2 3 4]


### 🔎 Hints
*(peek only if you need a nudge)*

- **C-order reshape:** default reshape is row-major — think “fill rows left→right.”  
- **Fortran-order reshape:** specify the memory order flag to fill columns top→bottom.  
- **From raw bytes:** there’s a constructor that views a `bytes` object as an array without copying; make sure to set the dtype to 8-bit unsigned.

### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*

In [2]:
# Section 4 solutions

def make_reshape_c_order():
    a = np.arange(6)               # [0,1,2,3,4,5]
    return a.reshape(2, 3)         # C-order by default

def make_reshape_f_order():
    a = np.arange(1, 7)            # [1,2,3,4,5,6]
    return a.reshape(2, 3, order="F")

def make_frombuffer_uint8():
    return np.frombuffer(b"\x01\x02\x03\x04", dtype=np.uint8)


## Section 5 — Stacking & Splitting

You can make arrays — now let’s **compose** them.  
In this section you’ll practice:

- *stacking rows and columns*  
- *stacking along a new depth axis*  
- *and splitting arrays back into equal parts*

This is the glue you’ll use to assemble mini-datasets and to break them down again.


### 🧩 Tasks
Write your functions below. Each one should return the described object.


In [3]:
# Section 5 tasks

import numpy as np

def make_vstack_rows_2x3():
    """
    Section 5 — Vertical stack (rows)
    - Create two 1D arrays: [1, 2, 3] and [4, 5, 6].
    - Stack them as rows to form a 2D array with shape (2, 3).
    - Row 0 should contain the first three numbers; row 1 the next three.
    """
    raise NotImplementedError


def make_hstack_cols_3x2():
    """
    Section 5 — Horizontal stack (columns)
    - Create two column vectors of shape (3, 1):
        col1 = [1, 2, 3]^T
        col2 = [10, 20, 30]^T
    - Stack them side-by-side to form shape (3, 2), with col1 then col2.
    """
    raise NotImplementedError


def make_stack_depth_2x2x2():
    """
    Section 5 — Stack along depth
    - Create two 2x2 arrays:
        A = [[1, 0],
             [0, 1]]      (identity pattern)
        B = [[2, 2],
             [2, 2]]      (all twos)
    - Stack them along a NEW last axis to get shape (2, 2, 2)
      so that out[:, :, 0] == A and out[:, :, 1] == B.
    """
    raise NotImplementedError


def make_split_1d_5_equal():
    """
    Section 5 — Split into equal chunks
    - Create a 1D array with integers 0..19 (inclusive).
    - Split it into 5 equal consecutive chunks (each length 4).
    - Return a tuple (chunk0, chunk1, chunk2, chunk3, chunk4).
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.


In [5]:
from tests.challenge_01 import section_05 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 1 failed")


Section 5 tests:

--- Vertical stack (rows) ---
✅ vstack: shape (2,3)
✅ vstack: first row [1,2,3]
✅ vstack: second row [4,5,6]
Output:
[[1 2 3]
 [4 5 6]]

--- Horizontal stack (columns) ---
✅ hstack: shape (3,2)
✅ hstack: first column [1,2,3]
✅ hstack: second column [10,20,30]
Output:
[[ 1 10]
 [ 2 20]
 [ 3 30]]

--- Stack along depth (2x2x2) ---
✅ depth-stack: shape (2,2,2)
✅ depth-stack: slice 0 == A
✅ depth-stack: slice 1 == B
Output:
[[[1 2]
  [0 2]]

 [[0 2]
  [1 2]]]

--- Split 1D array into 5 equal chunks ---
✅ split: tuple of 5 chunks
✅ split: each chunk has length 4
✅ split: concatenation is 0..19
Output:
(array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19]))


### 🔎 Hints
*(peek only if you need a nudge)*


- **Stacking rows vs columns:** think `vstack` (one row on top of another) and `hstack` (columns side-by-side).  
- **Column vectors:** give them shape `(n, 1)` — reshaping or `np.newaxis` can help.  
- **Depth stacking:** adding a new axis means “wrap both arrays together” — look for a function that stacks along an axis you choose.  
- **Equal splits:** when the total length divides evenly by the number of parts, use the strict split (not the version that tolerates uneven sizes).


### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*


In [4]:
# Section 5 solutions

def make_vstack_rows_2x3():
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    return np.vstack([a, b])

def make_hstack_cols_3x2():
    col1 = np.array([1, 2, 3]).reshape(-1, 1)
    col2 = np.array([10, 20, 30]).reshape(-1, 1)
    return np.hstack([col1, col2])

def make_stack_depth_2x2x2():
    A = np.array([[1, 0],
                  [0, 1]])
    B = np.full((2, 2), 2)
    return np.stack([A, B], axis=-1)

def make_split_1d_5_equal():
    arr = np.arange(20)  # 0..19
    parts = np.split(arr, 5)  # equal chunks only
    return tuple(parts)
