# Challenge 1 — Creating Your First Arrays

Welcome to the very first challenge!  
Before we can do anything interesting with NumPy, we need to know how to **make arrays**.  

In this challenge you’ll practice building arrays in different ways:  

- turning a Python list into a NumPy array
- generating sequences of numbers
- filling shapes with zeros, ones, or constants
- and trying a few tricks with diagonals and reshaping

Don’t worry if this feels new — every task will give you a **clear goal** and **instant feedback**.  
Your job is just to try writing the array, run the tests, and adjust until it works.

Think of this as your **“Hello World” moment with NumPy** — by the end you’ll be comfortable making the **building blocks** we’ll use in every other challenge.  


## Example — Arrays from a Python List

Let’s warm up with the simplest possible task:
Take a regular Python list and turn it into a NumPy array.

This shows you the basic pattern we’ll repeat throughout the drills:

1. Write your function.
2. Run the tests.
3. Adjust until everything passes.

In [1]:
import numpy as np

def example_make_array_from_list():
    """Return a NumPy array created from [1, 2, 3, 4, 5]."""
    return np.array([1, 2, 3, 4, 5])


### ✅ Test it

In [2]:
assert np.array_equal(example_make_array_from_list(), np.array([1,2,3,4,5]))
print("It works! ✅")

It works! ✅


## Section 1 — Sequences & Spacing

**Goal:** Get comfortable with sequence-generation. The patterns you are about to learn are the backbone of synthetic data, grid search, and plotting.

### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
import numpy as np

def make_odds_10_to_30():
    """
    Section 1 — Odds 11..29
    - Return a 1D array of odd integers strictly between 10 and 30.
    - Starts at 11 and ends at 29.
    - Step size = +2 (strictly increasing).
    """
    raise NotImplementedError


def make_linspace_unit_interval_101():
    """
    Section 1 — Linspace 0..1
    - Return a 1D array of length 101.
    - First value = 0.0, last value = 1.0.
    - Even spacing throughout (constant difference).
    - dtype must be float32.
    """
    raise NotImplementedError


def make_logspace_decades_0_to_3():
    """
    Section 1 — Logspace 10^0..10^3
    - Return a 1D array of length 4.
    - First value = 1 (10^0), last value = 1000 (10^3).
    - Constant ratio between consecutive values (×10).
    - dtype must be float64.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.


In [11]:
from tests.challenge_01 import section_01 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 1 failed")


Section 1 tests:

--- Odds 11..29 ---
✅ odds: 1D array
✅ odds: size 10
✅ odds: first=11, last=29
✅ odds: all odd
Output:
[11 13 15 17 19 21 23 25 27 29]

--- Linspace 0..1 (101 pts) ---
✅ linspace: length 101
✅ linspace: dtype float32
✅ linspace: endpoints 0 and 1
Output:
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]

--- Logspace 10^0..10^3 ---
✅ logspace: length 4
✅ logspace: dtype float64
✅ logspace: endpoints 1 and 1000
Output:
[   1.   10.  100. 1000.]


### 🔎 Hints
*(peek only if you need a nudge)*  

- **Odds sequence:** you want numbers that increase by 2, starting at 11, and stopping just before 30.  
- **Even spacing (count-based):** think of dividing the interval [0, 1] into exactly 100 equal gaps, and include both ends.  
- **Log spacing:** you want 4 numbers that grow by powers of 10, starting at 1 and ending at 1000. Try the function that generates values evenly on a log scale.


### 🧠 Reference Solutions

*(peek only after all tests pass — compare with your work, don’t just copy)*

In [10]:
# --- Reference Solutions for Section 1 ---
import numpy as np

def make_odds_10_to_30():
    return np.arange(11, 30, 2)

def make_linspace_unit_interval_101():
    return np.linspace(0.0, 1.0, 101, dtype=np.float32)

def make_logspace_decades_0_to_3():
    return np.logspace(0, 3, 4, dtype=np.float64)


## Section 2 — DTypes & Initialization

Now that you can make simple arrays, the next step is to control **what type of data** goes inside them and how the array is **initialized**.  

**Goal:** Learn that NumPy arrays aren’t just “numbers in boxes” — they carry **data type** information that changes how calculations behave.  


### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
import numpy as np

def make_zeros_int16_3x2():
    """
    Section 2 — Zeros matrix
    - Return a 2D array with shape (3,2).
    - All values must be 0.
    - dtype must be int16.
    """
    raise NotImplementedError


def make_full_pi_float32_2x3():
    """
    Section 2 — Full of π
    - Return a 2D array with shape (2,3).
    - Every value equals π (within float32 precision).
    - dtype must be float32.
    """
    raise NotImplementedError


def make_int8_range_neg5_to_4():
    """
    Section 2 — Range -5..4
    - Return a 1D array of consecutive integers from -5 up to +4 (inclusive).
    - Step size = +1 (strictly increasing).
    - dtype must be int8.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [13]:
from tests.challenge_01 import section_02 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 2 failed")


Section 2 tests:

--- Zeros int16 (3x2) ---
✅ zeros: shape (3,2)
✅ zeros: dtype int16
✅ zeros: all 0
Output:
[[0 0]
 [0 0]
 [0 0]]

--- Full of π float32 (2x3) ---
✅ pi: shape (2,3)
✅ pi: dtype float32
✅ pi: values equal π
Output:
[[3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927]]

--- Range -5..4 int8 ---
✅ range: length 10
✅ range: dtype int8
✅ range: endpoints -5 and 4
✅ range: consecutive +1
Output:
[-5 -4 -3 -2 -1  0  1  2  3  4]


### 🔎 Hints
*(peek only if you need a nudge)*  


- **Zeros with dtype:** there’s a constructor that creates an all-zeros array given a shape; you can set the dtype explicitly.
- **Fill with a constant:** prefer a constructor that fills an array with a single value in one shot; make sure the value and the array share the same precision.
- **Integer range:** think of creating a sequence from -5 up to (but not including) 5 and *fixing the dtype* to an 8-bit integer.

### 🧠 Reference Solutions (click to expand)

*(peek only after all tests pass — compare with your work, don’t just copy)*

In [12]:
# --- Reference Solutions for Section 2 ---
import numpy as np

def make_zeros_int16_3x2():
    return np.zeros((3, 2), dtype=np.int16)

def make_full_pi_float32_2x3():
    return np.full((2, 3), np.float32(np.pi), dtype=np.float32)

def make_int8_range_neg5_to_4():
    return np.arange(-5, 5, dtype=np.int8)


## Section 3 — Diagonals & Triangular Structure

**Goal:** Learn how to make various patterns that are commonly used in **linear algebra** and **martix multiplication**.

### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
import numpy as np

def make_eye4():
    """
    Section 3 — Identity 4x4
    - Return a 2D array with shape (4,4).
    - Ones on the main diagonal.
    - Zeros everywhere else.
    - Any numeric dtype is fine.
    """
    raise NotImplementedError


def make_band_main_and_upper():
    """
    Section 3 — Banded (main=1, upper=3)
    - Return a 2D array with shape (4,4).
    - Main diagonal values == 1.
    - First upper diagonal (k=+1) values == 3.
    - All other positions == 0.
    - Any numeric dtype is fine.
    """
    raise NotImplementedError


def make_tril_mask5_exclusive():
    """
    Section 3 — Strict lower-triangular mask
    - Return a boolean 2D array with shape (5,5).
    - Below main diagonal (i > j) == True.
    - On/above main diagonal (i <= j) == False.
    - dtype must be bool.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [15]:
from tests.challenge_01 import section_03 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 3 failed")


Section 3 tests:

--- Identity 4x4 ---
✅ eye4: shape (4,4)
✅ eye4: numeric dtype
✅ eye4: diagonal is 1
✅ eye4: exactly 4 non-zero elements
Output:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

--- Banded (main=1, upper=3) ---
✅ band: shape (4,4)
✅ band: numeric dtype
✅ band: main diagonal is 1
✅ band: upper diagonal is 3
✅ band: exactly 7 non-zero elements
Output:
[[1. 3. 0. 0.]
 [0. 1. 3. 0.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]

--- Strict lower-triangular mask ---
✅ tril: shape (5,5)
✅ tril: boolean dtype
✅ tril: (0,0) is False (on diagonal)
✅ tril: (1,0) is True (below diagonal)
✅ tril: (0,1) is False (above diagonal)
Output:
[[False False False False False]
 [ True False False False False]
 [ True  True False False False]
 [ True  True  True False False]
 [ True  True  True  True False]]


### 🔎 Hints
*(peek only if you need a nudge)*  

- **Identity matrix:** there’s a one-liner constructor for an “eye” with 1s on the main diagonal.  
- **Banded matrix:** try adding two arrays together — one for the main diagonal, one shifted up by 1.  
- **Lower-triangular mask:** there’s a helper that fills below the diagonal with ones; give it `k=-1` to exclude the diagonal and set `dtype=bool`.


### 🧠 Reference Solutions

*(peek only after all tests pass — compare with your work, don’t just copy)*

In [14]:
# --- Reference Solutions for Section 3 ---
import numpy as np

def make_eye4():
    return np.eye(4)

def make_band_main_and_upper():
    return np.eye(4) + np.diag(np.full(3, 3), k=1)

def make_tril_mask5_exclusive():
    return np.tril(np.ones((5,5), dtype=bool), k=-1)


## Section 4 — Reshape & Memory Order

**Goal:** Understand the layout of the data stored **in memory**. This matters for performance and interoperability.

### 💡 Info — C-contiguous vs F-contiguous

When reshaping, NumPy needs to decide how values are laid out in memory:

- **C-contiguous (row-major)** → default in NumPy. Values are stored row by row.  
  Example 2×3: stored as `[1, 2, 3, 4, 5, 6]`.  
- **F-contiguous (column-major)** → Values are stored column by column.  
  Same 2×3: stored as `[1, 4, 2, 5, 3, 6]`.

Why it matters: performance (cache-friendly iteration), interop with other languages, and reshaping results.  
👉 In practice, it affects **speed of operations** and **compatibility with external libraries**.


### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
import numpy as np

def make_reshape_c_order():
    """
    Section 4 — C-order reshape
    - Start from the sequence [0, 1, 2, 3, 4, 5].
    - Reshape into a 2D array with shape (2, 3) using default (row-major / C-order).
    - Expected row layout (conceptually): first row has the first three values, second row the next three.
    - The result should be C-contiguous in memory.
    """
    raise NotImplementedError


def make_reshape_f_order():
    """
    Section 4 — Fortran-order reshape
    - Start from the sequence [1, 2, 3, 4, 5, 6].
    - Reshape into a 2D array with shape (2, 3) using column-major (Fortran) order.
    - Expected column layout (conceptually): first column is [1, 2], second [3, 4], third [5, 6].
    - The result should be Fortran-contiguous in memory.
    """
    raise NotImplementedError


def make_frombuffer_uint8():
    """
    Section 4 — From raw bytes
    - Construct an array of dtype uint8 from the bytes b"\x01\x02\x03\x04".
    - The result should be a 1D array with those four values, in order.
    - No Python loops.
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.

In [2]:
from tests.challenge_01 import section_04 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 4 failed")


Section 4 tests:

--- C-order reshape ---
✅ c_order: 2D array
✅ c_order: shape (2,3)
✅ c_order: C-contiguous
✅ c_order: first row [0,1,2]
✅ c_order: second row [3,4,5]
Output:
[[0 1 2]
 [3 4 5]]

--- F-order reshape ---
✅ f_order: 2D array
✅ f_order: shape (2,3)
✅ f_order: F-contiguous
✅ f_order: first column [1,2]
✅ f_order: second column [3,4]
✅ f_order: third column [5,6]
Output:
[[1 3 5]
 [2 4 6]]

--- From buffer uint8 ---
✅ frombuffer: 1D array
✅ frombuffer: dtype uint8
✅ frombuffer: size 4
✅ frombuffer: first two values
✅ frombuffer: last two values
Output:
[1 2 3 4]


### 🔎 Hints
*(peek only if you need a nudge)*

- **C-order reshape:** default reshape is row-major — think “fill rows left→right.”  
- **Fortran-order reshape:** specify the memory order flag to fill columns top→bottom.  
- **From raw bytes:** there’s a constructor that views a `bytes` object as an array without copying; make sure to set the dtype to 8-bit unsigned.

### 🧠 Reference Solutions

*(peek only after all tests pass — compare with your work, don’t just copy)*

In [1]:
# --- Reference Solutions for Section 4 ---
import numpy as np

def make_reshape_c_order():
    a = np.arange(6)               # [0,1,2,3,4,5]
    return a.reshape(2, 3)         # C-order by default

def make_reshape_f_order():
    a = np.arange(1, 7)            # [1,2,3,4,5,6]
    return a.reshape(2, 3, order="F")

def make_frombuffer_uint8():
    return np.frombuffer(b"\x01\x02\x03\x04", dtype=np.uint8)


## Section 5 — Stacking & Splitting

**Goal:** Become familiar with techniques you'll often use in order to assemble mini-datasets and break them down again.

### 🧩 Tasks
Write your functions below. Each one should return the described object.


In [ ]:
import numpy as np

def make_vstack_rows_2x3():
    """
    Section 5 — Vertical stack (rows)
    - Create two 1D arrays: [1, 2, 3] and [4, 5, 6].
    - Stack them as rows to form a 2D array with shape (2, 3).
    - Row 0 should contain the first three numbers; row 1 the next three.
    """
    raise NotImplementedError


def make_hstack_cols_3x2():
    """
    Section 5 — Horizontal stack (columns)
    - Create two column vectors of shape (3, 1):
        col1 = [1, 2, 3]^T
        col2 = [10, 20, 30]^T
    - Stack them side-by-side to form shape (3, 2), with col1 then col2.
    """
    raise NotImplementedError


def make_stack_depth_2x2x2():
    """
    Section 5 — Stack along depth
    - Create two 2x2 arrays:
        A = [[1, 0],
             [0, 1]]      (identity pattern)
        B = [[2, 2],
             [2, 2]]      (all twos)
    - Stack them along a NEW last axis to get shape (2, 2, 2)
      so that out[:, :, 0] == A and out[:, :, 1] == B.
    """
    raise NotImplementedError


def make_split_1d_5_equal():
    """
    Section 5 — Split into equal chunks
    - Create a 1D array with integers 0..19 (inclusive).
    - Split it into 5 equal consecutive chunks (each length 4).
    - Return a tuple (chunk0, chunk1, chunk2, chunk3, chunk4).
    """
    raise NotImplementedError


### ✅ Tests
Run these right after you code. If they all pass, you’re good.


In [2]:
from tests.challenge_01 import section_05 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 5 failed")


Section 5 tests:

--- Vertical stack (rows) ---
✅ vstack: 2D array
✅ vstack: shape (2,3)
✅ vstack: first row [1,2,3]
✅ vstack: second row [4,5,6]
Output:
[[1 2 3]
 [4 5 6]]

--- Horizontal stack (columns) ---
✅ hstack: 2D array
✅ hstack: shape (3,2)
✅ hstack: first column [1,2,3]
✅ hstack: second column [10,20,30]
Output:
[[ 1 10]
 [ 2 20]
 [ 3 30]]

--- Stack along depth ---
✅ depth: 3D array
✅ depth: shape (2,2,2)
✅ depth: first slice is identity
✅ depth: second slice is all 2s
Output:
[[[1 2]
  [0 2]]

 [[0 2]
  [1 2]]]

--- Split 1D into 5 equal parts ---
✅ split: returns tuple
✅ split: 5 chunks
✅ split: all 1D arrays
✅ split: each chunk size 4
✅ split: first chunk [0,1,2,3]
✅ split: second chunk [4,5,6,7]
✅ split: last chunk [16,17,18,19]
Output:
(array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19]))


### 🔎 Hints
*(peek only if you need a nudge)*


- **Stacking rows vs columns:** think `vstack` (one row on top of another) and `hstack` (columns side-by-side).  
- **Column vectors:** give them shape `(n, 1)` — reshaping or `np.newaxis` can help.  
- **Depth stacking:** adding a new axis means “wrap both arrays together” — look for a function that stacks along an axis you choose.  
- **Equal splits:** when the total length divides evenly by the number of parts, use the strict split (not the version that tolerates uneven sizes).


### 🧠 Reference Solutions

*(peek only after all tests pass — compare with your work, don’t just copy)*

In [1]:
# --- Reference Solutions for Section 5 ---
import numpy as np

def make_vstack_rows_2x3():
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    return np.vstack([a, b])

def make_hstack_cols_3x2():
    col1 = np.array([1, 2, 3]).reshape(-1, 1)
    col2 = np.array([10, 20, 30]).reshape(-1, 1)
    return np.hstack([col1, col2])

def make_stack_depth_2x2x2():
    A = np.array([[1, 0],
                  [0, 1]])
    B = np.full((2, 2), 2)
    return np.stack([A, B], axis=-1)

def make_split_1d_5_equal():
    arr = np.arange(20)  # 0..19
    parts = np.split(arr, 5)  # equal chunks only
    return tuple(parts)


## Summary

Congratulations! You've completed **Challenge 1** and learned the fundamental skills for creating NumPy arrays. Here's what you've mastered:

### 🎯 **Key Skills Acquired**

**1. Array Creation from Sequences**
- `np.arange()` for integer sequences with custom start, stop, and step
- `np.linspace()` for evenly spaced floating-point values
- `np.logspace()` for logarithmically spaced values
- Understanding the difference between count-based vs. value-based spacing

**2. Data Types & Initialization**
- `np.zeros()` and `np.full()` for creating arrays with specific values
- Controlling data types with `dtype` parameter (int16, float32, etc.)
- Understanding how data types affect memory usage and precision

**3. Special Matrix Patterns**
- `np.eye()` for identity matrices
- `np.diag()` for diagonal matrices and banded structures
- `np.tril()` for triangular masks
- Building complex patterns by combining simple operations

**4. Memory Layout & Reshaping**
- C-order (row-major) vs F-order (column-major) memory layouts
- `reshape()` with different memory orders
- `np.frombuffer()` for creating arrays from raw bytes
- Understanding how memory layout affects performance

**5. Array Assembly & Decomposition**
- `np.vstack()` and `np.hstack()` for combining arrays
- `np.stack()` for adding new dimensions
- `np.split()` for breaking arrays into equal chunks
- Working with different array shapes and dimensions

### 🧠 **Core Concepts**

- **Arrays are more than just lists** — they carry type information and have specific memory layouts
- **Shape matters** — understanding how data is organized in memory affects both performance and results
- **NumPy's power comes from vectorization** — operations work on entire arrays, not individual elements
- **Data types control precision and memory** — choose the right type for your use case

### 🚀 **What's Next**

These array creation skills form the foundation for everything else in NumPy:
- **Challenge 2** will build on this with array operations and mathematical functions
- **Real-world applications** like data analysis, machine learning, and scientific computing
- **Performance optimization** by understanding memory layouts and data types

You now have the building blocks to create any array structure you need for your data science journey! 🎉