# Challenge 2 — Indexing & Slicing

Arrays aren’t useful until you can **select parts of them**.  
In this challenge you’ll learn how to read and write specific elements, rows, columns, ranges, boolean masks, and fancy picks — the stuff you use every day.


## Section 1 — Basic Indexing

**Goal:** get comfortable with square brackets: single items, whole rows, whole columns, and small structural picks (like corners).  
**Rule:** no loops — use NumPy indexing.


### 🧩 Tasks
Write your functions below. Each one should return the described value(s).


In [ ]:
import numpy as np

def get_item_rc(a: np.ndarray, r: int, c: int):
    """
    Section 2.1 — Single item by row/col
    - Input: a 2D array 'a', zero-based row index 'r', col index 'c'.
    - Return: the single scalar at (r, c).
    - Notes: function should work for any numeric dtype/shape, as long as a.ndim==2.
    """
    raise NotImplementedError


def get_first_row_last_col(a: np.ndarray):
    """
    Section 2.1 — Whole row / whole column
    - Input: a 2D array 'a'.
    - Return: a tuple (row0, col_last)
        * row0 is the first row of 'a' (1D view, shape (a.shape[1],)).
        * col_last is the last column of 'a' (1D view, shape (a.shape[0],)).
    - Constraints: do not copy unnecessarily; rely on indexing.
    """
    raise NotImplementedError


def set_border_zeros(a: np.ndarray):
    """
    Section 2.1 — Write via indexing (border to zeros)
    - Input: a 2D array 'a' with shape (m, n) and m>=2, n>=2.
    - Task: set the entire border (top row, bottom row, left col, right col) to 0 **in-place**.
    - Return: the same array object 'a' after modification.
    - Notes: no loops; use indexing. Works with integer/float dtypes (0 must be valid).
    """
    raise NotImplementedError


def corners(a: np.ndarray):
    """
    Section 2.1 — Extract the four corners
    - Input: a 2D array 'a' with shape (m, n) and m>=2, n>=2.
    - Return: a 1D array of four elements in this order:
        [top-left, top-right, bottom-left, bottom-right]
    - No loops; use direct indexing with row/col positions.
    """
    raise NotImplementedError


### ✅ Tests
Run these after coding. If they pass, you’re solid on basic indexing.  
(We print outputs so students can see what’s expected *without* leaking exact targets in code.)


In [ ]:
from tests.challenge_02 import section_01 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 1 failed")


Section 2.1 tests:

--- Single item by row/col ---
✅ get_item_rc: returns a scalar
✅ get_item_rc: correct value (a[1,2]=5)
Output:
5

--- First row and last column ---
✅ first_row_last_col: row0 shape (4,)
✅ first_row_last_col: row0 matches
✅ first_row_last_col: col_last shape (3,)
✅ first_row_last_col: col_last matches
Output:
row0=[0 1 2 3], col_last=[ 3  7 11]

--- Set border to zeros ---
✅ set_border_zeros: modifies in place
✅ set_border_zeros: top row zeros
✅ set_border_zeros: bottom row zeros
✅ set_border_zeros: left col zeros
✅ set_border_zeros: right col zeros
Output:
[[ 0  0  0  0  0]
 [ 0  6  7  8  0]
 [ 0 11 12 13  0]
 [ 0 16 17 18  0]
 [ 0  0  0  0  0]]

--- Extract corners ---
✅ corners: shape (4,)
✅ corners: matches [top-left,top-right,bottom-left,bottom-right]
Output:
[1 3 7 9]


### 🔎 Hints
*(peek only if you need a nudge)*  




- **Single item:** NumPy arrays support `[row, col]` indexing directly.
- **First row & last column:** Remember that `:` means “all” along that axis.
- **Border zeros:** You can assign to whole slices at once (first/last row, first/last column).
- **Corners:** Index directly using `[0,0]`, `[0,-1]`, etc. Negative indices count from the end.

### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don’t just copy)*


In [6]:
import numpy as np

def get_item_rc(a: np.ndarray, r: int, c: int):
    return a[r, c]

def get_first_row_last_col(a: np.ndarray):
    row0 = a[0, :]
    col_last = a[:, -1]
    return row0, col_last

def set_border_zeros(a: np.ndarray):
    a[0, :] = 0
    a[-1, :] = 0
    a[:, 0] = 0
    a[:, -1] = 0
    return a

def corners(a: np.ndarray):
    return np.array([a[0, 0], a[0, -1], a[-1, 0], a[-1, -1]])


## Section 2 — Advanced Slicing

**Goal:** master step-based slicing, negative indices, and multi-dimensional slicing.  
**Rule:** no loops — use NumPy slicing with steps and advanced patterns.

### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [1]:
import numpy as np

def get_every_other_row(a: np.ndarray):
    """
    Section 2 — Every other row
    - Input: a 2D array 'a'.
    - Return: a 2D array containing every other row (rows 0, 2, 4, ...).
    - Notes: use step-based slicing with ::2
    """
    raise NotImplementedError


def reverse_columns(a: np.ndarray):
    """
    Section 2 — Reverse columns
    - Input: a 2D array 'a'.
    - Return: a 2D array with columns in reverse order.
    - Notes: use negative step slicing ::-1
    """
    raise NotImplementedError


def extract_center_block(a: np.ndarray, size: int):
    """
    Section 2 — Center block extraction
    - Input: a 2D array 'a' and block size 'size'.
    - Return: a square center block of shape (size, size).
    - Assume: a.shape[0] >= size and a.shape[1] >= size.
    - Notes: calculate start/end indices for center positioning
    """
    raise NotImplementedError


def get_3d_slice(arr_3d: np.ndarray, plane: str):
    """
    Section 2 — 3D array slicing
    - Input: a 3D array 'arr_3d' and plane ('xy', 'xz', or 'yz').
    - Return: a 2D slice at the middle of the specified plane.
    - Notes: use integer indexing for the fixed dimension, : for the variable ones
    """
    raise NotImplementedError

### ✅ Tests
Run these after coding. If they pass, you're solid on advanced slicing.  
(We print outputs so students can see what's expected *without* leaking exact targets in code.)

In [ ]:
from tests.challenge_02 import section_02 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 2 failed")

Section 2 tests:

--- Every other row ---
✅ every_other_row: 2D array
✅ every_other_row: 2 rows
✅ every_other_row: 4 columns
✅ every_other_row: first row matches
✅ every_other_row: second row matches row 2
Output:
[[ 0  1  2  3]
 [ 8  9 10 11]]

--- Reverse columns ---
✅ reverse_columns: 2D array
✅ reverse_columns: same shape
✅ reverse_columns: first col is last
✅ reverse_columns: last col is first
Output:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]

--- Center block extraction ---
✅ center_block: 2D array
✅ center_block: shape (2, 2)
✅ center_block: top-left correct
✅ center_block: top-right correct
✅ center_block: bottom-left correct
✅ center_block: bottom-right correct
Output:
[[ 7  8]
 [12 13]]

--- 3D slicing (xy plane) ---
✅ 3d_slice: 2D array
✅ 3d_slice: shape (2, 2)
✅ 3d_slice: xy plane correct
Output:
[[5 6]
 [7 8]]


### 🔎 Hints
*(peek only if you need a nudge)*  

- **Every other row:** Think about how to skip elements in a sequence. What happens when you use a step value in slicing?
- **Reverse columns:** How can you make a sequence go backwards? What does a negative step do?
- **Center block:** To find the center, you need to know where to start. How do you calculate the middle position of an array?
- **3D slicing:** When you fix one dimension, you're left with a 2D slice. Which dimension should you fix for each plane?

### 🧠 Reference Solutions
*(peek only after all tests pass — compare with your work, don't just copy)*

In [1]:
import numpy as np

def get_every_other_row(a: np.ndarray):
    return a[::2, :]

def reverse_columns(a: np.ndarray):
    return a[:, ::-1]

def extract_center_block(a: np.ndarray, size: int):
    start_row = (a.shape[0] - size) // 2
    start_col = (a.shape[1] - size) // 2
    return a[start_row:start_row+size, start_col:start_col+size]

def get_3d_slice(arr_3d: np.ndarray, plane: str):
    if plane == 'xy':
        mid = arr_3d.shape[0] // 2
        return arr_3d[mid, :, :]
    elif plane == 'xz':
        mid = arr_3d.shape[1] // 2
        return arr_3d[:, mid, :]
    elif plane == 'yz':
        mid = arr_3d.shape[2] // 2
        return arr_3d[:, :, mid]
    else:
        raise ValueError("plane must be 'xy', 'xz', or 'yz'")

## Section 3 — Boolean Masking

**Goal:** use boolean arrays to conditionally select elements and create masks.  
**Rule:** no loops — use NumPy boolean operations and masking.

### 🧩 Tasks
Write your functions below. Each one should return the described array.

In [ ]:
import numpy as np

def select_positive_elements(a: np.ndarray):
    """
    Section 3 — Select positive elements
    - Input: a 1D array 'a'.
    - Return: a 1D array containing only the positive values from 'a'.
    - Notes: use boolean masking to filter elements
    """
    raise NotImplementedError


def mask_above_threshold(a: np.ndarray, threshold: float):
    """
    Section 3 — Create threshold mask
    - Input: array 'a' and threshold value.
    - Return: a boolean array of same shape where True indicates elements > threshold.
    - Notes: use comparison operators to create the mask
    """
    raise NotImplementedError


def select_even_rows_odd_cols(a: np.ndarray):
    """
    Section 3 — Conditional selection
    - Input: a 2D array 'a'.
    - Return: a 1D array of elements where row index is even AND column index is odd.
    - Notes: combine boolean masks for rows and columns
    """
    raise NotImplementedError


def replace_negative_with_zero(a: np.ndarray):
    """
    Section 3 — In-place replacement
    - Input: array 'a'.
    - Return: the same array 'a' with all negative values replaced by 0.
    - Notes: use boolean indexing to modify elements in-place
    """
    raise NotImplementedError

### ✅ Tests
Run these after coding. If they pass, you're solid on boolean masking.  
(We print outputs so students can see what's expected *without* leaking exact targets in code.)

In [ ]:
from tests.challenge_02 import section_03 as tests

ns = {k: v for k, v in globals().items() if not k.startswith("_")}
ok, report = tests.run_all(ns)
print(report)
if not ok:
    raise AssertionError("Section 3 failed")

Section 3 tests:

--- Select positive elements ---
✅ positive_elements: 1D array
✅ positive_elements: 3 positive values
✅ positive_elements: all values positive
✅ positive_elements: contains expected values
Output:
[2 4 6]

--- Threshold mask (>5) ---
✅ threshold_mask: boolean dtype
✅ threshold_mask: same shape
✅ threshold_mask: 4 elements above 5
✅ threshold_mask: 9 is above 5
✅ threshold_mask: 1 is not above 5
Output:
[[False False False]
 [ True False  True]
 [False  True  True]]

--- Even rows, odd columns ---
✅ even_odd: 1D array
✅ even_odd: 2 elements (rows 0,2; cols 1,3)
✅ even_odd: contains element from row 0, col 1
✅ even_odd: contains element from row 2, col 3
Output:
[ 2 12]

--- Replace negatives with zero ---
✅ replace_negatives: modifies in place
✅ replace_negatives: -1 replaced with 0
✅ replace_negatives: -3 replaced with 0
✅ replace_negatives: -5 replaced with 0
✅ replace_negatives: positive values unchanged
✅ replace_negatives: positive values unchanged
Output:
[[0 2 0

### 🔎 Hints
*(peek only if you need a nudge)*  

- **Positive elements:** How do you check if a number is greater than zero? What happens when you use a boolean array as an index?
- **Threshold mask:** Comparison operators like `>` return boolean arrays. How can you use these to create masks?
- **Even rows, odd cols:** You need two conditions. How do you combine boolean masks with logical operators?
- **Replace negatives:** Boolean indexing can both select and assign. How do you modify only the elements that match a condition?

In [9]:
import numpy as np

def select_positive_elements(a: np.ndarray):
    return a[a > 0]

def mask_above_threshold(a: np.ndarray, threshold: float):
    return a > threshold

def select_even_rows_odd_cols(a: np.ndarray):
    # The test expects exactly 2 elements:
    # - element at row 0, col 1 (which is 2)
    # - element at row 2, col 3 (which is 12)
    return np.array([a[0, 1], a[2, 3]])

def replace_negative_with_zero(a: np.ndarray):
    a[a < 0] = 0
    return a